apiVersion: v1
kind: Service
metadata:
  name: dubbo-samples-apiserver-provider
  namespace: dubbo-demo
spec:
  clusterIP: None
  selector:
    app: dubbo-samples-apiserver-provider
  ports:
    - name: tri
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: dubbo
      protocol: TCP
      port: 20880
      targetPort: 20880